apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: NodePort
  selector:
    app: laravel-mysql
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080    # Access at <NodeIP>:30080
